name: Publish site

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup dependencies
        run: sudo apt install -y librsvg2-bin pngquant && bun i -g svgo
      - name: Build
        run: sh/site.sh
      - name: Bundle
        run: cd site && bun install && bun run build
      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/dist
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
